<template>
  <MonacoEditor
    class="ml-editor"
    ref="editor"
    v-model="text"
    :theme="theme"
    @editorWillMount="willMount"
    @editorDidMount="didMount"
    @change="textChange"
    language="markdown"
  />
</template>

<script>
import MonacoEditor from "vue-monaco";

// this.$refs.editor.getEditor()
export default {
  components: {
    MonacoEditor
  },

  data() {
    return {
      text: "",
      theme: "vs",
      colorMap: {
        staff: "#594d5e",
        pyon: "#ea5b76",
        mocho: "#ed90ba",
        kraz: "#6495cf"
      }
    };
  },
  methods: {
    willMount() {},
    didMount() {},
    textChange(t) {
      this.text = t;
      this.$refs.editor.getEditor().updateOptions();
    },
    reverseColor(color) {
      if (typeof color !== "string") {
        throw "color must be a string";
      } else if (!color.match(/^#?[0-9a-fA-F]{6}$/)) {
        throw "invalid color format";
      } else if (color.length === 7) {
        color = color.substr(1);
      }
      return [5, 6, 3, 4, 1, 2]
        .map(i => color[i - 1])
        .join("")
        .toUpperCase();
    },
    style(name, color, position = 2) {
      return `Style: ${name},方正准圆_GBK,35,&H00${this.reverseColor(
        color
      )},&H00FF0000,&H00FFFFFF,&H00000000,0,0,0,0,100,100,0,0,1,2,2,${position},10,10,10,1`;
    },
    line(text) {
      return `Dialogue: 0,0:00:00.00,0:00:00.00,Default,,0,0,0,,${text}`;
    }
  },
  computed: {
    ass() {
      return `[Script Info]
; Script generated by Aegisub 3.2.2
; http://www.aegisub.org/
Title: Default Aegisub file
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
YCbCr Matrix: None

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
${this.style("标注", "#B6B3B2", 7)}
${Object.entries(this.colorMap)
  .map(([key, value]) => this.style(key, value))
  .join("\n")}

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
${(() => {
  const ans = this.text
    .split("\n")
    .map(l => this.line(l))
    .join("\n");
  console.log(ans);
  return ans;
})()}
`;
    }
  }
};
</script>

<style lang="scss" scoped>
.ml-editor {
  overflow: hidden;
  width: 100vw;
  height: 90vh;
}
</style>
